# Generated by Django 2.2.1 on 2019-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.TextField(max_length=50)),
                ('file', models.FileField(upload_to='reference_lib/')),
            ],
        ),
        migrations.DeleteModel(
            name='RefLibrary',
        ),
    ]
