# Generated by Django 2.2.1 on 2019-05-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190524_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reference_lib/'),
        ),
    ]
