# Generated by Django 2.2.1 on 2019-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='fileName',
            field=models.CharField(max_length=100),
        ),
    ]
