# Generated by Django 2.2.1 on 2019-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_query_queryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryFile',
            field=models.FileField(null=True, upload_to='queryFiles/'),
        ),
    ]
