# Generated by Django 2.2.1 on 2019-05-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20190530_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryFile',
            field=models.FileField(blank=True, null=True, upload_to='queryFiles/'),
        ),
    ]
